### ISSUE TITLE
Running on WSL 2

### ISSUE THREAD

**Issue by rheajt** [OfficeDev/microsoft-teams-app-quickstarts#21] opened 2020-08-16 08:23 UTC
The "Debugger for Chrome" dependency in VS Code prevents the Teams Toolkit extension from loading. For some reason the Teams toolkit installs on WSL and the Debugger extension installs locally. There doesn't seem to be a way to install them both in the same environment manually. 

![Imgur](https://i.imgur.com/6wkgzdZ.png)

I have the Debugger installed in both environments, however, the way the Teams toolkit extension loads the dependency, it gets deactivated in favor the of the local installation. I have tried removing everything but to no avail.

**Comment by rheajt** [comment] 2020-08-21 06:09
Is this project dead?

**Comment by asnow003** [comment] 2020-08-24 20:09
Thank you for the message.  So I can get a good idea of your environments and installation scenario can you describe your environments.  I am not sure exactly what your problem is.

**Comment by rheajt** [comment] 2020-08-28 06:52
Thanks for the reply,

OS: Windows 10
Program: VS Code

Using the Windows Subsystem for Linux and the remote connection extension for VS Code. There is a dependency for the Chrome Debugger that makes the extension unusable. I reverted the Teams Toolkit extension to 1.0.1 and it works again.

The error message I posted above is what happens with the recent version of the teams toolkit.

**Comment by tiagoboeing** [comment] 2020-09-11 13:48
Works in WSL 2 with 1.0.1 and 1.0.3. Now i using v1.0.3.

**Comment by ankitbko** [comment] 2020-11-27 18:01
@asnow003 Any update on this issue?

**Comment by karthigb** [comment] 2020-11-30 18:51
Hi everyone,

Thank you for your patience. The Chrome and Edge debuggers have been disabled in VSC for remote connections. We originally did not include either in our package.json as an extension dependency which is why the earlier versions worked. The problem is that people had to manually download the debuggers themselves. 

This scenario won't be supported until the Edge and Chrome debuggers are supported for remote connections.

**Closed by karthigb** 2020-11-30 18:51 UTC
