### ISSUE TITLE
"Bot Management" tab loading infinitely 

### ISSUE THREAD

**Issue by fedsp** [OfficeDev/microsoft-teams-app-quickstarts#34] opened 2020-10-26 16:29 UTC
Hi, I'm trying to connect my current fully functional bot (using azure and bot framework of course) to a custom teams app. 
However, one of the steps described [here](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot) asks to click on the 'Bot management' button and insert the bot endpoint address.

I can't do it. Once I click on it, the spinner keeps spinning but nothing happened: Not a message, not a warning, nothing.
What can I do to troubleshoot that better? Tested with several different computers (all of them win10 using the last vscode version), and the results are all the same.

![image](https://user-images.githubusercontent.com/22076750/97199901-517f6e00-178f-11eb-9b9d-15b9e6b3cb19.png)

**Comment by asnow003** [comment] 2020-10-26 17:04
Sorry you have run into this issue...we should have a fix for this in a day or two.  Can you try signing out and back in again in the extension to see if that resolves the issue....

Also, as a workaround if you have access to App Studio in Teams you can use the "Bot Management" feature there as well to finish the setup process...

**Comment by fedsp** [comment] 2020-10-26 19:04
Thank you for the quick reply, Allen!
I will proceed using the App Studio in teams meanwhile.

**Comment by fedsp** [comment] 2020-10-28 20:47
Hi @asnow003 , there is any news on this particular scenario? Seems like a backend issue common both on vscode and the teams appstudio, because I'm having the exact same issue:
![image](https://user-images.githubusercontent.com/22076750/97494804-96e59c00-1945-11eb-9e0f-c9312a6c0452.png)

**Comment by asnow003** [comment] 2020-10-28 20:58
When was the last time you tried....we did have an issue on our service side that was causing the endless spinner.  Can you try this again in the teams toolkit extension in VS Code or App Studio again.

**Comment by fedsp** [comment] 2020-10-28 21:05
It was just some minutes ago! Both on VsCode and MsTeams

**Comment by karthigb** [comment] 2020-10-28 22:12
@fedsp Which version of the toolkit are you using? I can't seem to reproduce.

**Comment by fedsp** [comment] 2020-10-29 00:43
Vscode: 1.50.1
Extension: 1.1

**Comment by asnow003** [comment] 2020-10-29 03:51
Thank you for reporting this I think I have figured out the issue.  It is happening if you have never created a bot before with that account you are logged in as.

A workaround to this would be to go into app studio...create a test app.  Go to bots and setup a new bot.  Grab the bot id and password from there.  Sorry about the inconvenience....working on a fix for that ASAP.

**Comment by asnow003** [comment] 2020-10-30 00:41
This should be resolved now with the latest update.  It will no longer spin indefinite.  You have the option now to create a new bot.  One small fix coming soon is that we will hide/disable the dropdown for existing bots since you have never created one.

**Closed by asnow003** 2020-10-30 00:41 UTC
